/* jshint node: true */
'use strict';

/**
  # sdp-lines

  This is a simple
  [SDP](http://en.wikipedia.org/wiki/Session_Description_Protocol) library
  designed for in-place modification of sdp lines.

  ## Why?

  SDP parsing in browsers is relatively brittle (and not currently compliant
  with the latest SDP RFC: [4566](http://tools.ietf.org/html/rfc4566)). This
  library has been developed as an __interim__ approach for dealing with SDP
  generated by a browser.

  It follows the following rules:

  - The order of SDP lines is never modified (in order = out order)

  - SDP lines are not modified unless a specific tweak requires modifying the
    line.  That is, a line is not parsed and regenerated unless a particular
    modification operation requires it.

  - Any new lines added to the SDP are added either after existing lines of
    the same time (for instance `a` lines), or if no other lines exist within
    the relevant scope, then immediately after the line type specified in the
    4566 RFC.

  ## Example Usage

  To be completed.

  ## Alternative Options

  If you are looking for an SDP parser which works with an intermediate JS
  object format, then any of the libraries below will do what you need:

  - https://github.com/clux/sdp-transform
  - https://github.com/legastero/sdp
  - https://github.com/buildar/getting_started_with_webrtc
**/

module.exports = function(input) {

};